version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

volumes:
  mongodb_data:
