version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mysql
    environment:
      DOMAIN: ${DOMAIN}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql  # Use service name as the host
      DB_NAME: ${DB_NAME}
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
